spring:
  application:
    name: employee

  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: Jaggu@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto=update:
